config/routes.rb
Rails.application.routes.draw do
  
  get 'about' => 'welcome#about'

  root 'wikis#index'
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :wikis, :users, :charges
  
end

app/models/charge.rb
class Charge < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :wikis
  
  after_create :welcome_send
  
  enum role: [:standard, :premium, :admin]
  
  after_initialize :set_default_role, :if => :new_record?
  
  def set_default_role
    self.role ||= :standard
  end

  def welcome_send
    WelcomeMailer.welcome_send(self).deliver_now
  end
  
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  include Pundit
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  private
  
    def user_not_authorized
      flash[:alert] = "Access denied"
      redirect_to (request.referrer || root_path)
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  
  def index
  end

  def new
  end

  def create
    
    @amount = 1500
    
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]  
    )
 
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Blocipedia Premium Member',
      :currency    => 'usd'
    )
    
    current_user.update_attribute(:role, 'premium') 

    if current_user.save!
      flash[:notice] = "Thanks for upgrading, #{current_user.firstname}! You're now a lifetime #{current_user.role.capitalize} member!"
      redirect_to wikis_path
    end

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end
  
  def destroy
    
    @wikis = current_user.wikis
    @wikis.update_all(private: false)

    current_user.update_attribute(:role, 'standard')
    
    redirect_to root_path, notice: "You have cancelled your Premium membership."
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  private

  def sign_up_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end
  
  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => 'User deleted'
  end
    
  def update
    @user = User.find(params[:id])
    authorize @user
    
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => 'User updated'
    else
      redirect_to users_path, :alert => 'Unable to update user'
    end
  end
  
  private
  
    def secure_params
      params.require(:user).permit(:role)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = Wiki.all.reverse
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = current_user.wikis.build(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end
   
  def edit
    @wiki = Wiki.find(params[:id])
  end
  
  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end
  
  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end
  
  private
    def wiki_params
      params.require(:wiki).permit(:title, :body, :private)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    return markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper

  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                    count: resource.errors.count,
                    resource: resource.class.model_name.human.downcase)

   html = <<-HTML
   <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML
 
    html.html_safe
  end

end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$15.00</strong> to Blocipedia!  You're now a <strong>premium member</strong>!</h2>

app/views/charges/new.html.erb
<div>
  <h3>Sign Up to Be a Premium Blocipedia User</h3>
</div>
<div>
  <h4>Post Unlimited Private Wikis!</h4>    
</div>
<div>
  <%= form_tag charges_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <span>Lifetime Subscription: $15.00</span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Lifetime Subscription"
            data-amount="1500"
            data-locale="auto"></script>
  <% end %></br></br>
  <button><%= link_to 'No Thanks', root_path, :class => 'button right' %></button>, take me to the Wikis.
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  
    <% if user_signed_in? %>
      Welcome, <strong><%= current_user.firstname %> <%= current_user.lastname %></strong>! |
      <%= link_to 'Your Account', current_user, :class => 'navbar-link' %> | <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </head>
<body>

  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocipedia", root_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>
    
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
     
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <td>
      <button><%= f.submit 'Change Account Level' %></button>
      <% unless user == current_user %>
        <button><%= link_to("Delete User", user_path(user), :data => { :confirm => "Are you sure?"}, :method => :delete, :class => "button") %></button>
      <% end %></br></br>
    </td>
  <% end %>
</td>

app/views/users/index.html.erb
<h3>All Users</h3>
<% @users.each do |user| %>
  <tr>
    <%= render user %>
  </tr>
<% end %>

app/views/users/show.html.erb
<div>
  <h3>User</h3>
</div>
<div>
  <p>Name: <%= @user.firstname %> <%= @user.lastname %></p>
  <p>Email: <%= @user.email  %></p>
  <p>Account Level: <%= @user.role.capitalize %></p>
  <button><%= link_to 'Edit Profile', edit_user_registration_path, :class => 'button right' %></button></br></br>
  <% if @user.role == "standard" %>
    <p><strong>Want to post private Wikis?  Upgrade to Premium now!</strong></p>
    <button><%= link_to 'Upgrade to Premium', new_charge_path, :class => 'button right' %></button>
  <% end %>
  <% if @user.role == "premium" %>
    <p>Want to cancel your Premium membership?</p>
   <%= link_to 'Downgrade to Standard Membership', charge_path, :data => { :confirm => "Are you sure?"}, :method => :delete %>
  <% end %>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome to Blocipedia!</h1>

<p>This is a placeholder.</p>

<p>
If you'd like to go to the list of wikis, please input
https://blocipedia-rjp203.c9users.io/wikis into your browser.
</p>

<p>
If you'd like to create a new wiki, please input 
https://blocipedia-rjp203.c9users.io/wikis/new into your browser.
</p>

<p>Enjoy!</p>

app/views/wikis/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for Wikis</p>
    <ul>
      <li>Make sure all information is true.  No fake news!</li>
      <li>No foul language, please.</li>
    </ul>
  </div>
  <div class="col-md-8">
  <%= form_for @wiki do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki title" %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter Wiki body" %>
    </div>
    <% if current_user.admin? || current_user.premium? %>
      <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %> Private Wiki
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/wikis/edit.html.erb
<h3>Edit Wiki</h3>
  <div>
    <%= render 'form' %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>Welcome to Blocipedia!</h1>

<h3>All Wikis</h3>
  <%= link_to "Create New Wiki", new_wiki_path(@wiki), class: 'btn btn-success' %>
  <% @wikis.each do |wiki| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <% if current_user.role == "standard" %>
            <% if wiki.private == false %>
              <%= link_to wiki.title, wiki %>
            <% else %>
              "<%= wiki.title %>" is a private Wiki.  Upgrade your membership to view.
            <% end %>
          <% else %>            
            <%= link_to wiki.title, wiki %>
          <% end %>
        </h4>
      </div>
    </div>
  <% end %>

app/views/wikis/new.html.erb
<h3>New Wiki</h3>
  <div>
    <%= render 'form' %>
  </div>
</div>

app/views/wikis/show.html.erb
<h3><%= @wiki.title %></h3>

<% if @wiki.private == true && current_user.role == "standard" %>
  <div>
    <h3>This is a private Wiki.  You must be a Premium member to view.</h3>
    <h4>Click the button below to become a Premium member so you can view and create private Wikis!</h4>
      <button><%= link_to 'Upgrade to Premium', new_charge_path, :class => 'button right' %></button>
        </br></br>
      <button><%= link_to 'No Thanks', root_path, :class => 'button right' %></button>, take me to the public Wikis.
  </div>
<% else %>
  <div>
    <% if @wiki.user %>
      <h6 class="indent"></indent>by <%= @wiki.user.firstname %> <%= @wiki.user.lastname %></h6>
      <% if @wiki.private == true %>
        <h6 class="indent">This Wiki is <strong>Private</strong>.</h6>
      <% end %>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-8">
      <%= markdown(@wiki.body) %>
    </div>
  
    <div class="col-md-4">
      <%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} if policy(@wiki).destroy?%>
    </div>
  </div>
<% end %>